[features]
seeds = false
skip-lint = false

[programs.localnet]
exploit_0 = "3pk8v8gn15mTQqiaWrLTQgnnaaKtS3CPfCirLcLS8Jzj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
